# -*- coding: utf-8 -*-
"""LPC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnPkxds4qtHq2KSUM8Rbp9YSOT6LReXS
"""

content = """
eyJuIjogIlJlYmVjYSBCYXJyaW9zICIsICJmIjogZmFsc2UsICJ2X3AiOiBbIk1hcl8xMi0xNCJdLCAidl9kIjogWyJNYXJfMTItMTQiXX0=

eyJuIjogIkx1Y2lhbm8gUGFsZW5jaWEgIiwgImYiOiBmYWxzZSwgInZfcCI6IFsiTHVuXzEyLTE0IiwgIkx1bl8xNC0xNiIsICJNYXJfMTItMTQiLCAiTWFyXzE0LTE2IiwgIkp1ZV8xMi0xNCJdLCAidl9kIjogWyJMdW5fMTItMTQiLCAiTHVuXzE0LTE2IiwgIk1hcl8wOC0xMCJdfQ==

eyJuIjogIlNhbWFudGhhIFBhcnJhIiwgImYiOiB0cnVlLCAidl9wIjogWyJMdW5fMTAtMTIiLCAiSnVlXzA4LTEwIl0sICJ2X2QiOiBbIkx1bl8xMC0xMiJdfQ==

eyJuIjogIkFuZHJcdTAwZTlzIE1lbmRvemEgIiwgImYiOiB0cnVlLCAidl9wIjogWyJNYXJfMTItMTQiXSwgInZfZCI6IFsiTWFyXzEwLTEyIl19

eyJuIjogIkVsaWV6ZXIgVmVsYXNxdWV6IiwgImYiOiBmYWxzZSwgInZfcCI6IFsiTHVuXzA4LTEwIiwgIkx1bl8xMC0xMiIsICJMdW5fMTItMTQiLCAiTHVuXzE0LTE2IiwgIk1pZV8wOC0xMCIsICJNaWVfMTAtMTIiLCAiTWllXzEyLTE0IiwgIk1pZV8xNC0xNiIsICJWaWVfMDgtMTAiLCAiVmllXzEwLTEyIiwgIlZpZV8xMi0xNCIsICJWaWVfMTQtMTYiXSwgInZfZCI6IFsiTWFyXzA4LTEwIiwgIk1hcl8xMC0xMiIsICJNYXJfMTItMTQiLCAiTWFyXzE0LTE2IiwgIkp1ZV8wOC0xMCIsICJKdWVfMTAtMTIiLCAiSnVlXzEyLTE0IiwgIkp1ZV8xNC0xNiJdfQ==

eyJuIjogIllhcmlhbmEgT3JvemNvIiwgImYiOiBmYWxzZSwgInZfcCI6IFsiTHVuXzEyLTE0IiwgIkp1ZV8xMC0xMiJdLCAidl9kIjogWyJMdW5fMTItMTQiLCAiSnVlXzEyLTE0Il19

eyJuIjogIkRlbmljZSBWaWxjaGV6ICIsICJmIjogdHJ1ZSwgInZfcCI6IFsiSnVlXzEwLTEyIl0sICJ2X2QiOiBbIkp1ZV8xMC0xMiJdfQ==

eyJuIjogIkZyYW5jbyBKYWltZXMiLCAiZiI6IGZhbHNlZSwgInZfcCI6IFsiTWFyXzA4LTEwIiwgIk1hcl8xMC0xMiIsICJNYXJfMTItMTQiLCAiTWFyXzE0LTE2IiwgIkp1ZV8xMi0xNCIsICJWaWVfMDgtMTAiXSwgInZfZCI6IFsiTWFyXzEwLTEyIiwgIk1hcl8xMi0xNCIsICJNYXJfMTQtMTYiLCAiSnVlXzEyLTE0Il19

eyJuIjogIlphcmFoIEFsdmFyYWRvIiwgImYiOiBmYWxzZSwgInZfcCI6IFsiTWllXzE0LTE2IiwgIkp1ZV8xMC0xMiJdLCAidl9kIjogWyJNaWVfMTQtMTYiLCAiSnVlXzEwLTEyIl19

eyJuIjogIkNlYnJpXHUwMGUxbiBJcmlhcnRlIiwgImYiOiBmYWxzZSwgInZfcCI6IFsiTWFyXzEyLTE0IiwgIk1hcl8xNC0xNiIsICJKdWVfMDgtMTAiLCAiSnVlXzEwLTEyIiwgIlZpZV8wOC0xMCIsICJWaWVfMTAtMTIiLCAiVmllXzEyLTE0IiwgIlZpZV8xNC0xNiJdLCAidl9kIjogWyJNYXJfMTQtMTYiLCAiSnVlXzA4LTEwIiwgIlZpZV8wOC0xMCJdfQ==

eyJuIjogIlJvaW5lciBSb3NhcmlvICIsICJmIjogdHJ1ZSwgInZfcCI6IFsiTHVuXzEyLTE0IiwgIk1hcl8xMi0xNCJdLCAidl9kIjogW119

eyJuIjogIk1hdXJvIE1lbGVhbiAiLCAiZiI6IGZhbHNlLCAidl9wIjogWyJNYXJfMDgtMTAiLCAiTWFyXzEwLTEyIiwgIk1pZV8xMC0xMiIsICJNaWVfMTItMTQiXSwgInZfZCI6IFsiTWllXzEwLTEyIiwgIk1pZV8xMi0xNCJdfQ==

eyJuIjogIkplc1x1MDBmYXMgU3VcdTAwZTFyZXoiLCAiZiI6IGZhbHNlLCAidl9wIjogWyJMdW5fMTAtMTIiLCAiTHVuXzEyLTE0IiwgIk1hcl8wOC0xMCIsICJNYXJfMTAtMTIiLCAiTWFyXzEyLTE0IiwgIk1pZV8xMi0xNCIsICJKdWVfMTAtMTIiLCAiSnVlXzEyLTE0Il0sICJ2X2QiOiBbIkx1bl8xMC0xMiIsICJMdW5fMTItMTQiLCAiTWFyXzA4LTEwIiwgIk1hcl8xMC0xMiIsICJNYXJfMTItMTQiLCAiSnVlXzEwLTEyIiwgIkp1ZV8xMi0xNCJdfQ==

eyJuIjogIkVmcmFpbiBBcnJpZWNodSIsICJmIjogZmFsc2UsICJ2X3AiOiBbIkx1bl8xMC0xMiIsICJMdW5fMTItMTQiLCAiTHVuXzE0LTE2IiwgIk1hcl8wOC0xMCIsICJNYXJfMTAtMTIiLCAiTWFyXzEyLTE0IiwgIk1hcl8xNC0xNiIsICJKdWVfMTAtMTIiLCAiSnVlXzEyLTE0IiwgIkp1ZV8xNC0xNiJdLCAidl9kIjogWyJMdW5fMTAtMTIiLCAiSnVlXzEwLTEyIl19

eyJuIjogIlJlYmVjYSBIZXJuYW5kZXogIiwgImYiOiBmYWxzZSwgInZfcCI6IFsiTWFyXzEyLTE0IiwgIkp1ZV8xMi0xNCJdLCAidl9kIjogWyJNYXJfMDgtMTAiLCAiSnVlXzEyLTE0Il1dfQ==

eyJuIjogIkFsdmVyaXMgRWRtdW5kbyBMXHUwMGYzcGV6IGx1Z28gIiwgImYiOiBmYWxzZSwgInYiOiBbIkx1bl8xMi0xNCIsICJNYXJfMTItMTQiLCAiTWllXzEyLTE0IiwgIkp1ZV8xMi0xNCIsICJWaWVfMTItMTQiXX0=

eyJuIjogIkp1YW4gUmFtaXJleiAiLCAiZiI6IGZhbHNlLCAidl9wIjogWyJMdW5fMTItMTQiLCAiTWFyXzA4LTEwIl0sICJ2X2QiOiBbIk1pZV8xMi0xNCIsICJKdWVfMTItMTQiLCAiVmllXzEyLTE0Il19

eyJuIjogIk1pcmFuZGEgTW9udGVybyAiLCAiZiI6IGZhbHNlLCAidl9wIjogWyJNYXJfMTAtMTIiLCAiTWllXzEwLTEyIiwgIkp1ZV8xMC0xMiIsICJWaWVfMTAtMTIiLCAiVmllXzEyLTE0Il0sICJ2X2QiOiBbIk1hcl8xMC0xMiIsICJNYXJfMTItMTQiLCAiTWllXzEwLTEyIiwgIlZpZV8xMC0xMiIsICJWaWVfMTItMTQiXX0=
"""

with open('votos.txt', 'w') as f:
    f.write(content.strip())

print("votos.txt created successfully.")

import base64
import json
import re
import os
import numpy as np
import matplotlib.pyplot as plt

# Universo completo de bloques horarios de la semana
BLOQUES_SEMANA = [
    "Lun_08-10", "Lun_10-12", "Lun_12-14", "Lun_14-16",
    "Mar_08-10", "Mar_10-12", "Mar_12-14", "Mar_14-16",
    "Mie_08-10", "Mie_10-12", "Mie_12-14", "Mie_14-16",
    "Jue_08-10", "Jue_10-12", "Jue_12-14", "Jue_14-16",
    "Vie_08-10", "Vie_10-12", "Vie_12-14", "Vie_14-16"
]

def cargar_y_procesar_votos(archivo_ruta):
    if not os.path.exists(archivo_ruta):
        print(f"❌ Error: El archivo '{archivo_ruta}' no se encuentra en el entorno de Colab.")
        return []

    estudiantes = []
    with open(archivo_ruta, 'r', encoding='utf-8') as f:
        contenido = f.read()

    # Extrae las cadenas Base64 de longitud considerable
    tokens_encontrados = re.findall(r'[A-Za-z0-9+/]{40,}=*', contenido)
    print(f"🔍 Se encontraron {len(tokens_encontrados)} posibles tokens en el archivo.")

    for i, token in enumerate(tokens_encontrados):
        try:
            datos_bytes = base64.b64decode(token)
            voto_crudo = json.loads(datos_bytes.decode('utf-8'))

            nombre = voto_crudo.get('n', f"Estudiante_{i+1}")
            es_foraneo = voto_crudo.get('f', False)
            votos_pueden = voto_crudo.get('v_p', [])
            votos_desean = voto_crudo.get('v_d', [])

            horarios_estudiante = {}
            for bloque in BLOQUES_SEMANA:
                if bloque in votos_desean:
                    horarios_estudiante[bloque] = "Quiero"
                elif bloque in votos_pueden:
                    horarios_estudiante[bloque] = "Puedo"
                else:
                    horarios_estudiante[bloque] = "No puedo"

            estudiantes.append({
                "nombre": nombre,
                "tipo": "foraneo" if es_foraneo else "local",
                "horarios": horarios_estudiante
            })
        except Exception as e:
            continue

    return estudiantes

def simular_consenso(estudiantes):
    pesos_foraneo = np.arange(1.0, 10.1, 0.1)
    lista_Wf, lista_U_total, lista_ISN, bloques_ganadores = [], [], [], []

    for Wf in pesos_foraneo:
        mejor_bloque = None
        max_bienestar = -float('inf')
        mejor_isn = 0.0

        for bloque in BLOQUES_SEMANA:
            u_bloque = 0.0
            pueden_asistir = 0
            quieren_y_asisten = 0

            for est in estudiantes:
                voto = est['horarios'][bloque]
                peso = Wf if est['tipo'] == 'foraneo' else 1.0

                if voto == "Quiero":
                    puntos_base = 1.5
                    pueden_asistir += 1
                    quieren_y_asisten += 1
                elif voto == "Puedo":
                    puntos_base = 1.0
                    pueden_asistir += 1
                else:
                    puntos_base = -1.5

                u_bloque += puntos_base * peso

            if u_bloque > max_bienestar:
                max_bienestar = u_bloque
                mejor_bloque = bloque
                mejor_isn = (quieren_y_asisten / pueden_asistir * 100) if pueden_asistir > 0 else 0.0

        lista_Wf.append(Wf)
        lista_U_total.append(max_bienestar)
        lista_ISN.append(mejor_isn)
        bloques_ganadores.append(mejor_bloque)

    return lista_Wf, lista_U_total, lista_ISN, bloques_ganadores

def generar_grafica(Wf, U_total, ISN):
    fig, ax1 = plt.subplots(figsize=(10, 6))

    color = 'tab:blue'
    ax1.set_xlabel('Peso del Estudiante Foráneo ($W_f$)', fontsize=12)
    ax1.set_ylabel('Bienestar General ($U_{total}$)', color=color, fontsize=12)
    line1 = ax1.plot(Wf, U_total, color=color, linewidth=2.5, label='Bienestar General ($U_{total}$)')
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.grid(True, linestyle='--', alpha=0.5)

    ax2 = ax1.twinx()
    color = 'tab:red'
    ax2.set_ylabel('Índice de Satisfacción Neta ($ISN$ %)', color=color, fontsize=12)
    line2 = ax2.plot(Wf, ISN, color=color, linestyle=':', linewidth=2.5, label='Satisfacción Neta ($ISN$)')
    ax2.tick_params(axis='y', labelcolor=color)

    lineas = line1 + line2
    etiquetas = [l.get_label() for l in lineas]
    ax1.legend(lineas, etiquetas, loc='upper left')

    plt.title('Optimización de Horarios: Bienestar vs. Satisfacción Neta', fontsize=14, fontweight='bold')
    plt.tight_layout()

    # Guarda la imagen en el almacenamiento de Colab
    plt.savefig('grafica_consenso.png', dpi=300)
    print("💾 Gráfica guardada en Colab como 'grafica_consenso.png'")
    plt.show()

# Ejecución en el entorno
archivo_datos = "votos.txt"
datos_estudiantes = cargar_y_procesar_votos(archivo_datos)
print(f"📊 Se procesaron exitosamente {len(datos_estudiantes)} estudiantes.")

if datos_estudiantes:
    Wf, U_total, ISN, bloques = simular_consenso(datos_estudiantes)
    print("\n--- 🏛️ RESULTADOS ---")
    print(f"Bloque sugerido inicialmente (Wf = 1.0): {bloques[0]}")
    print(f"Bloque de consenso definitivo (Wf = 10.0): {bloques[-1]}")
    print("---------------------\n")
    generar_grafica(Wf, U_total, ISN)